name: BungeeCTW-Lobby
version: 1.0-ALPHA
main: com.mauccio.bctwl.CTWLobby
description: Mauccio's CTW Bungee Lobby Server
author: Mauccio
softdepend: [Vault, PlaceholderAPI]
commands:
  setlobby:
    description: Set lobby
    permission: ctwlobby.setlobby
    usage: /setlobby
    permission-message: You don't have <permission>
  ctw:
    description: Mauccios CTW main command.
    permission: ctw.admin
    usage: /ctw [reload|save|mapcycle]
    permission-message: You don't have <permission>
  spawn:
    description: Take players to spawn points.
    usage: /spawn
    permission-message: You don't have <permission>
  alert:
    description: Send an alert to the server.
    usage: /alert
    permission: ctw.admin
    permission-message: You don't have <permission>
    aliases: [al, alerta, aviso, avviso]
  stats:
    description: View your stats.
    usage: /stats
    permission: ctw.stats
    permission-message: You don't have <permission>
    aliases: [est, estadisticas, statistiche, sta]
  rooms:
    description: View the room list
    usage: /rooms
    permission: ctw.rooms
    permission-message: You don't have <permission>
permissions:
  ctw.vip:
    description: Gives vip accesories
    children:
      ctw.choseteam: true
      ctw.override-limit: true
      ctw.vip-armor: true
      ctw.kiteditor: true
      ctw:savekit: true
      ctw.rooms: true
      ctw.generalchat: true
      ctw.join: true
      ctw.stats: true
  ctw.player:
    description: Gives access to player Capture The Wool actions
    children:
      ctw.generalchat: true
      ctw.join: true
      ctw.stats: true
      ctw.kiteditor: true
      ctw:savekit: true
      ctw.rooms: true
  cts.admin:
    description: Gives access to player admin commmands
    children:
      ctw.setup: true
      ctw.receive-alerts: true
      ctw.admin: true
      ctw.globalkit: true
  ctw.*:
    description: Gives access to all Capture The Wool commands
    children:
      ctw.choseteam: true
      ctw.override-limit: true
      ctw.generalchat: true
      ctw.setup: true
      ctw.join: true
      ctw.admin: true
      ctw.ingame-extra-cmds: true
      ctw.vip-armor: true